openapi: '3.0.2'
info:
  title: hololinked system host server
  description: hololinked system host server stores system level data using this API. System level data allow interaction with one's system as a whole - where, what RemoteObject's are running and how? This API is also consumed by the hololinked-portal app, therefore containing services related to hololinked-portal.  
  version: '1.0.0'  
paths: {}
components:
  schemas:
    app-settings:
      type: object
      properties:
        dashboards:
          $ref: "#/components/schemas/dashboards"    
        login:
          $ref: "#/components/schemas/login"    
        servers:
          $ref: "#/components/schemas/servers"    
        remoteObjectViewer:
          $ref: "#/components/schemas/remoteObjectViewer"    
    dashboards:
          type: object
          properties:
            deleteWithoutAsking:
              type: boolean
            showRecentlyUsed:
              type: boolean
    login:
      type: object 
      properties:
        footer:
          type: string
          default: ""
        footerLink:
          type: string 
          default: ""
        displayFooter:
          type: boolean
    servers:
      type: object 
      properties:
        allowHTTP:
          type: boolean 
          default: false
    remoteObjectViewer:
      type: object 
      properties:
        console: 
          type: object
          properties:      
            stringifyOutput: 
              type: boolean 
              default: false
            defaultMaxEntries: 
              type: integer
              default: 15
            defaultWindowSize: 
              type: integer 
              default: 500
            defaultFontSize: 
              type: integer
              default : 16
        logViewer: 
          type: object
          properties:
            stringifyOutput: 
              type: boolean
              default: false
            defaultMaxEntries: 
              type: integer
              default: 10
            defaultWindowSize: 
              type: integer
              default: 1000
            defaultFontSize: 
              type: integer 
              default: 16
            