openapi: '3.0.2'
info:
  title: hololinked system host server
  description: hololinked system host server stores system level data using this API. System level data allow interaction with one's system as a whole - where, what RemoteObject's are running and how? This API is also consumed by the hololinked-portal app, therefore containing services related to hololinked-portal.  
  version: '1.0.0'
servers:
  - url: https://localhost:8080
    description: recommended
  - url: http://localhost:8080
paths:
  /app-settings:
    $ref: "./routes/app-settings.yml#/app-settings"  
  /app-settings/{name}:
    $ref: "./routes/app-settings.yml#/app-settings-with-name"  
  /users:
    $ref: "./routes/users.yml#/users"
  /login:
    $ref: "./routes/login.yml#/login"
  /logout:
    $ref: "./routes/login.yml#/logout"

components:
  schemas:
    app-settings: 
      $ref: "./schemas/app-settings.yml#/components/schemas/app-settings"
    users:
      $ref: "./schemas/users.yml#/components/schemas/users"
    login-data:
      $ref: "./schemas/users.yml#/components/schemas/login-data"
  securitySchemes:
    cookieAuth:
      $ref: "./schemas/users.yml#/components/securitySchemes/cookieAuth"