name: Unit Tests With TestPyPI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - release

    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: | 
          pip install jsonschema
          pip install -i https://test.pypi.org/simple/ hololinked==0.2.2
          
      - name: Run unit tests to verify if the release to TestPyPI is working
        run: |
          python -m unittest discover -s tests -p 'test_*.py'
        
              
 
