name: Unit Tests For Development

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

    
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Run unit tests and generate coverage report
        run: |
          pip install coverage
          coverage run -m unittest discover -s tests -p 'test_*.py'
          coverage report -m

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

              
 