name: Unit Tests With TestPyPI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - release

    
jobs:
  test:
    
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: | 
          pip install -r tests/requirements.txt
          pip install jsonschema
          pip install -i https://test.pypi.org/simple/ hololinked
          
      - name: Run unit tests to verify if the release to TestPyPI is working
        run: |
          python -m unittest discover -s tests -p 'test_*.py'
        
              
 
